---
- name: DO - Create Droplet
  digital_ocean: >
    state=present
    command=droplet
    name={{item}}
    size_id=2gb
    region_id=fra1
    image_id={{os}}
    ssh_key_ids={{ ansible_ssh_key.ssh_key.id }}
    private_networking=yes
    virtio=yes
    backups_enabled=yes
    unique_name=yes
    user_data={{ lookup('file', '{{cloud_config}}') | replace('SSH_KEY_PLACEHOLDER', ansible_ssh_key.ssh_key.public_key) }}
  register: droplet
- debug: msg="IP is {{ droplet.droplet.ip_address }} Private IP is {{droplet.droplet.private_ip_address}}"
- name: Wait for SSH
  local_action: wait_for port=22 host={{ droplet.droplet.ip_address }}
- name: DO - Add new droplet private ip to public group
  add_host: hostname={{ droplet.droplet.ip_address }} groupname={{group_public}}
- name: DO - Add new droplet private ip to private group
  add_host: hostname={{ droplet.droplet.private_ip_address }} groupname={{group_private}}
