- name: MS Core fonts accept EULA
  become: true
  become_method: sudo
  shell: echo ttf-mscorefonts-installer msttcorefonts/accepted-mscorefonts-eula select true | debconf-set-selections
- name: Install phantomjs
  become: true
  become_method: sudo
  apt: name={{item}} state=present
  with_items:
    - libfreetype6 
    - libfreetype6-dev 
    - libfontconfig 
    - libfontconfig-dev
    - phantomjs
    - ttf-mscorefonts-installer